//
//  HomeWorker.swift
//  VIP_TEST
//
//  Created by OuSS on 2/23/20.
//  Copyright (c) 2020 OuSS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker {
    
    func fetchArtists(completion: @escaping (Result<Artists.List.Response,Error>) -> ()) {
        let urlString = "https://rss.itunes.apple.com/api/v1/us/apple-music/coming-soon/all/10/explicit.json"
        
        guard let url = URL(string: urlString) else { return }
        
        URLSession.shared.dataTask(with: url) { (data, resp, error) in
            
            if let error = error {
                completion(.failure(error))
                return
            }
            
            guard let data = data else { return }
            
            do {
                let response = try JSONDecoder().decode(Artists.List.Response.self, from: data)
                completion(.success(response))
            } catch let error {
                completion(.failure(error))
                return
            }
        }.resume()
    }
}
