//
//  HomeModels.swift
//  VIP_TEST
//
//  Created by OuSS on 2/23/20.
//  Copyright (c) 2020 OuSS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Artists {
  // MARK: Use cases
    
    struct Feed: Codable {
        var results: [Artist]?
    }
    
    // MARK: - Use cases
    struct Artist: Codable {
        let artistName   : String
        let artworkUrl100       : String
        let kind          : String
    }
    
    enum List {
        struct Request {
        }
        
        struct Response: Codable {
            var feed: Feed
        }
        
        struct ViewModel {
            var artists: [Artist]?
        }
    }
}
