//
//  HomeInteractor.swift
//  VIP_TEST
//
//  Created by OuSS on 2/23/20.
//  Copyright (c) 2020 OuSS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
    func fetchArtists(request: Artists.List.Request)
}

protocol HomeDataStore
{
  //var name: String { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
  var presenter: HomePresentationLogic?
  var worker: HomeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func fetchArtists(request: Artists.List.Request)
  {
    worker = HomeWorker()
    worker?.fetchArtists(completion: { (result) in
        switch result {
        case .success(let response):
            self.presenter?.presentArtists(response: response)
        case .failure(let error):
            print(error)
            return
        }
    })
  }
}
